// DO NOT REARRANGE - VALUES ARE USED IN DB
export enum Action {
  USER_KICK = 0,
  USER_ROLE_ADD,
  USER_ROLE_REMOVE,
  USER_NICK_CHANGE,
  USER_ASSOCIATE,
  USER_REMOVE_ASSOCIATION,

  WARNING_ADD,
  WARNING_REMOVE,
  WARNING_UPDATE,

  EVENT_ADD,
  EVENT_REMOVE,
  EVENT_UPDATE,
  EVENT_POST,

  RECRUITMENTPOST_UPDATE
}
