name: lint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
    - name: Run ESLint
      run: pnpm lint
