name: lint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
    - name: Install modules
      run: pnpm
    - name: Run ESLint
      run: pnpm lint
