name: lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.2
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Run ESLint
        run: bun run lint
